### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by justinzelinsky** [nileshdas/terminalFootball#1]
Neat CLI! I'm looking at the code and can think of a few improvements. However, I noticed there are no tests. Might be worth looking into -- it'll be easy to ensure that any improvements made or refactoring done don't break any existing functionality.

**Comment by nileshdas** [comment]
Yeah, I was thinking about it too. would you like to work on it?

**Comment by justinzelinsky** [comment]
I'd be happy to offer advice or assist but I don't know the intent behind your code -- you do :) I'd be trying to reverse engineer your code to make tests. I may miss intent or edge cases.

Which testing library are you the most familiar with?

**Comment by nileshdas** [comment]
I will work on it ASAP
