### ISSUE TITLE
All commands resulting in "Sorry, an error occured. Please report issues to..."

### ISSUE THREAD

**Issue by isene** [nileshdas/terminalFootball#31]
## BUG REPORT
   Bug: All commands such as `/usr/local/bin/football standings -l PL` or `football fixtures -l PL -d 5 -t "Manchester United" -n` results in "Sorry, an error occured. Please report issues to https://github.com/nileshdas/terminalFootball/issues if problem persists."

### Versions
- NodeJS version: 10.19.0
- Football CLI version: 1.0.6

**Comment by nileshdas** [comment]
Did you get the API key first?

**Comment by isene** [comment]
Eh. Brainfart. Sorry.
